from ase.calculators.calculator import Calculator


class MMCalculator(Calculator):
    """MM calculator driven by an OpenMM System XML.

    Parameters
    ----------
    xml_set : MMXMLSet
        Paths to system.xml and integrator.xml generated by prepare_mm.
    """

    implemented_properties = ["energy", "forces"]

    def __init__(self, xml_set, **kwargs):
        super().__init__(**kwargs)
        self._system_xml = xml_set.system_xml
        self._integrator_xml = xml_set.integrator_xml

    def calculate(self, atoms, properties, system_changes):
        Calculator.calculate(self, atoms, properties, system_changes)
        raise NotImplementedError("MMCalculator.calculate must be implemented.")
